spring:
  application:
    name: rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
spring-doc:
  swagger-ui:
    paths-to-match: /api/**/v1/**
    path: /swagger-ui.html
logging:
  level:
    br.com.erudio: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG


