INSERT INTO Person (id, first_name, last_name, address, gender) VALUES
                                                                    (1, 'João', 'Silva', 'Rua das Flores, 123 - São Paulo/SP', 'Male'),
                                                                    (2, 'Maria', 'Oliveira', 'Av. Paulista, 1000 - São Paulo/SP', 'Female'),
                                                                    (3, 'Carlos', 'Santos', 'Rua Afonso Pena, 45 - Belo Horizonte/MG', 'Male'),
                                                                    (4, 'Ana', 'Souza', 'Rua XV de Novembro, 200 - Curitiba/PR', 'Female'),
                                                                    (5, 'Pedro', 'Costa', 'Av. Atlântica, 300 - Rio de Janeiro/RJ', 'Male'),
                                                                    (6, 'Juliana', 'Pereira', 'Rua das Palmeiras, 78 - Porto Alegre/RS', 'Female'),
                                                                    (7, 'Lucas', 'Rodrigues', 'Av. Brasil, 1500 - Fortaleza/CE', 'Male'),
                                                                    (8, 'Fernanda', 'Almeida', 'Rua Sete de Setembro, 321 - Salvador/BA', 'Female'),
                                                                    (9, 'Rafael', 'Lima', 'Av. Amazonas, 890 - Manaus/AM', 'Male'),
                                                                    (10, 'Patrícia', 'Gomes', 'Rua Goiás, 456 - Goiânia/GO', 'Female'),
                                                                    (11, 'Bruno', 'Ribeiro', 'Av. Beira Mar, 987 - Recife/PE', 'Male'),
                                                                    (12, 'Camila', 'Martins', 'Rua Sergipe, 654 - Vitória/ES', 'Female'),
                                                                    (13, 'Diego', 'Carvalho', 'Av. das Nações, 741 - Brasília/DF', 'Male'),
                                                                    (14, 'Larissa', 'Rocha', 'Rua Pará, 852 - Belém/PA', 'Female'),
                                                                    (15, 'Gustavo', 'Dias', 'Av. Independência, 963 - Campinas/SP', 'Male'),
                                                                    (16, 'Aline', 'Barbosa', 'Rua das Acácias, 159 - Florianópolis/SC', 'Female'),
                                                                    (17, 'Thiago', 'Nunes', 'Av. Central, 753 - São Luís/MA', 'Male'),
                                                                    (18, 'Renata', 'Teixeira', 'Rua Aurora, 258 - Natal/RN', 'Female'),
                                                                    (19, 'Felipe', 'Moreira', 'Av. Dom Pedro II, 369 - João Pessoa/PB', 'Male'),
                                                                    (20, 'Carla', 'Melo', 'Rua das Laranjeiras, 147 - Aracaju/SE', 'Female');